# Generated by Django 5.2.4 on 2025-07-08 15:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DifficultyLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WordList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word_list_name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["word_list_name"],
            },
        ),
        migrations.CreateModel(
            name="WordType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word_type", models.CharField(max_length=50, unique=True)),
                ("abbreviation", models.CharField(blank=True, max_length=10)),
            ],
            options={
                "ordering": ["word_type"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("google_id", models.CharField(blank=True, max_length=100, null=True)),
                ("first_name", models.CharField(blank=True, max_length=50)),
                ("last_name", models.CharField(blank=True, max_length=50)),
                ("profile_picture", models.URLField(blank=True, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=50)),
                ("user_timezone", models.CharField(blank=True, max_length=50)),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("premium", "Premium"),
                            ("pro", "Pro"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("subscription_expires", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WordsBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100, unique=True)),
                ("meaning_urdu", models.TextField()),
                ("meaning_english", models.TextField()),
                ("example_sentence", models.TextField()),
                (
                    "synonyms",
                    models.TextField(blank=True, help_text="Comma-separated synonyms"),
                ),
                (
                    "antonyms",
                    models.TextField(blank=True, help_text="Comma-separated antonyms"),
                ),
                ("pronunciation", models.CharField(blank=True, max_length=200)),
                ("etymology", models.TextField(blank=True)),
                (
                    "frequency_rank",
                    models.PositiveIntegerField(
                        blank=True, help_text="Word frequency ranking", null=True
                    ),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                ("times_reviewed", models.PositiveIntegerField(default=0)),
                ("last_reviewed", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "difficulty_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vocabulary.difficultylevel",
                    ),
                ),
                (
                    "word_lists",
                    models.ManyToManyField(blank=True, to="vocabulary.wordlist"),
                ),
                (
                    "word_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vocabulary.wordtype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Words Bank",
                "ordering": ["word"],
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mastery_level",
                    models.IntegerField(default=0, help_text="0-5 scale"),
                ),
                ("times_correct", models.PositiveIntegerField(default=0)),
                ("times_incorrect", models.PositiveIntegerField(default=0)),
                ("last_attempt", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vocabulary.wordsbank",
                    ),
                ),
            ],
            options={
                "unique_together": {("word", "user")},
            },
        ),
    ]
