# Generated by Django 5.2.4 on 2025-07-08 21:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocabulary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[("synonym", "Synonym"), ("antonym", "Antonym")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "word1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_as_word1",
                        to="vocabulary.wordsbank",
                    ),
                ),
                (
                    "word2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_as_word2",
                        to="vocabulary.wordsbank",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["word1", "relationship_type"],
                        name="vocabulary__word1_i_6d7962_idx",
                    ),
                    models.Index(
                        fields=["word2", "relationship_type"],
                        name="vocabulary__word2_i_f93e73_idx",
                    ),
                ],
                "unique_together": {("word1", "word2", "relationship_type")},
            },
        ),
    ]
